name: Schedule Netlify Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # Once a day around 9am ET
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        env:
          BUILD_KEY: ${{ secrets.NETLIFY_BUILD_KEY }}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/$env:BUILD_KEY
